### PR TITLE
Update trongate-datetime.js

### PR DESCRIPTION
**Pull request by ReDeLe-design**
use the new functions parseDate and parseDateTime to parse the input into a Date Object, using the format of the spezified locale in the global variable "localeString". Also use the locale to output the Date or DateTime as aspected.

### CODE REVIEW

**Comment by davidjconnelly** [comment]
Thank you for this.  I'd like to test it before pulling it in, if I may.  If you have time for a Skype call and you'd be able to walk me through what problem your code solves and what it does then I'd be super grateful and perhaps it could speed things up.  Thanks again.  I'm super grateful!

**Comment by ReDeLe-design** [comment]
>Hi, it would be a pleasure to guide you through my changes. I only have Teams as available tool for conferencing.
Would suit you on friday the 2022-08-26?  Please give  me a timeslot proposal in UTC+2.

**Comment by ReDeLe-design** [comment]
Errors with more than one Date-Picker / Clear Date
Changed the function "disableDatePickerInputs". 
The Line 670: var targetEl = datePickerInputs[i]; was responsible for the fact that targetEl was always pointing to the last Date-Input in a form. This was the main problem solved by using  "ev.target" instead inside the event handler.

Next problem was changing focus between two Date-Inout-Fields. The "mousedown" event of the next field occurs bevore the  "blure" event of the old field. That leads to storing the wrong value in the variable "originalValue". This was solved bei changing "mousedown" to "focus" event. Inside the blur event I am using now the new parseDate function to test for a valid Date.

The last Change was to have the possibility to clear a date input, for example in case of an optional field. Solved by testing for the  "Backspace" or "Delete" key in combination with testing for "ev.target.value.length == 0". So selecting the whole date-string and press Backspace works perfekt to clear a once selected Date.

**Comment by trongate** [comment]
Okay.  Apologies for not making that phone call with you.   I've had a look and I think your code is good.  Thank you!   Congratulations on becoming a contributor.   Welcome to the revolution!

**Pull request merged**
